## server properties
server:
  port: 9090

# db properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_sql_practice?useSSL=false&verifyServerCertificate=false&noAccessToProcedureBodies=true
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  hazelcast:
    config: hazelcast.xml